import 'package:get/get.dart';

class AppTranslations extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        ///------------------------------------------------------------------English
        'en': {
          "Hey, Welcome Back !": "Hey, Welcome Back !",
          "Powered By": "Powered By",
          "Novasoft Technologies": "Novasoft Technologies",
          "Phone Number": "Phone Number",
          "Please enter your Phone No.": "Please enter your Phone No.",
          "Password": "Password",
          "Please enter your Password": "Please enter your Password",
          "Forgot password ?": "Forgot password ?",
          "Log In": "Log In",
          "Don't have an account? ": "Don't have an account? ",
          "Register": "Register",
          "Forgot Password": "Forgot Password",
          "Get OTP": "Get OTP",
          "Create an account !": "Create an account !",
          "Your Name": "Your Name",
          "Please enter your Name": "Please enter your Name",
          "Company Name": "Company Name",
          "Please enter your Company Name": "Please enter your Company Name",
          "Address": "Address",
          "Please enter your Company Address":
              "Please enter your Company Address",
          "VAT Number": "VAT Number",
          "Please enter your VAT No.": "Please enter your VAT No.",
          "CR Number": "CR Number",
          "Please enter your CR No.": "Please enter your CR No.",
          "Email": "Email",
          "Please enter your Email": "Please enter your Email",
          "Confirm Password": "Confirm Password",
          "Please enter Password to confirm":
              "Please enter Password to confirm",
          "Already have an account?": "Already have an account?",
          "Nahla Online": "Nahla Online",
          "What are you looking for?": "What are you looking for?",
          "Invoices": "Invoices",
          "Home": "Home",
          "Download": "Download",
          "Choose your Language": "Choose your Language",
          "English": "English",
          "Arabic": "Arabic",
        },

        ///---------------------------------------------------------------------------------- Arabic
        'ar': {
          "Hey, Welcome Back !": "مرحبًا بعودتك!",
          "Powered By": "مدعوم من",
          "Novasoft Technologies": "نوفاسوفت تكنولوجيز",
          "Phone Number": "رقم التليفون",
          "Please enter your Phone No.": "الرجاء إدخال رقم هاتفك",
          "Password": "كلمة المرور",
          "Please enter your Password": "الرجاء إدخال كلمة المرور الخاصة بك",
          "Forgot password ?": "هل نسيت كلمة السر ؟ ",
          "Log In": "تسجيل الدخول",
          "Don't have an account? ": "ليس لديك حساب؟",
          "Register": "يسجل",
          "Forgot Password": "هل نسيت كلمة السر",
          "Get OTP": "",
          "Create an account !": "إنشاء حساب !",
          "Your Name": "اسمك",
          "Please enter your Name": "",
          "Company Name": "",
          "Please enter your Company Name": "",
          "Address": "",
          "Please enter your Company Address": "",
          "VAT Number": "",
          "Please enter your VAT No.": "",
          "CR Number": "",
          "Please enter your CR No.": "",
          "Email": "",
          "Please enter your Email": "",
          "Confirm Password": "",
          "Please enter Password to confirm": "",
          "Already have an account?": "",
          "Nahla Online": "",
          "What are you looking for?": "",
          "Invoices": "",
          "Home": "",
          "Download": "",
          "Choose your Language": "اختر لغتك",
          "English": "الإنجليزية",
          "Arabic": "عربي",
        },
      };
}
