import 'package:get/get.dart';

class AppTranslations extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        ///------------------------------------------------------------------English
        'en': {
          "Hey, Welcome Back !": "Hey, Welcome Back !",
          "Powered By": "Powered By",
          "Novasoft Technologies": "Novasoft Technologies",
          "Phone Number": "Phone Number",
          "Please enter your Phone No.": "Please enter your Phone No.",
          "Password": "Password",
          "Please enter your Password": "Please enter your Password",
          "Forgot password ?": "Forgot password ?",
          "Login": "Login",
          "Don't have an account? ": "Don't have an account? ",
          "Register": "Register",
          "Forgot Password": "Forgot Password",
          "Get OTP": "Get OTP",
          "Create an account !": "Create an account !",
          "Your Name": "Your Name",
          "Please enter your Name": "Please enter your Name",
          "Company Name": "Company Name",
          "Please enter your Company Name": "Please enter your Company Name",
          "Address": "Address",
          "Please enter your Company Address":
              "Please enter your Company Address",
          "VAT Number": "VAT Number",
          "Please enter your VAT No.": "Please enter your VAT No.",
          "CR Number": "CR Number",
          "Please enter your CR No.": "Please enter your CR No.",
          "Email": "Email",
          "Please enter your Email": "Please enter your Email",
          "Confirm Password": "Confirm Password",
          "Please enter Password to confirm":
              "Please enter Password to confirm",
          "Already have an account?": "Already have an account?",
          "Nahla Online": "Nahla Online",
          "What are you looking for?": "What are you looking for?",
          "Invoices": "Invoices",
          "Home": "Home",
          "Download": "Download",
          "Choose your Language": "Choose your Language",
          "English": "English",
          "Arabic": "Arabic",
          "OTP Verification": "OTP Verification",
          "Enter the OTP sent to": "Enter the OTP sent to",
          "Verify": "Verify",
          "Orders": "Orders",
          "Order No : ": "Order No : ",
          "Amount : ": "Amount : ",
          "Status : ": "Status : ",
          "Last Updated : ": "Last Updated : ",
          "Add New Invoice": "Add New Invoice",
          "Required field": "Required field",
          "Please enter your Inv No.": "Please enter your Inv No.",
          "--- OR ---": "--- OR ---",
          "Tap below barcode to start scan": "Tap below barcode to start scan",
          "Add Order": "Add Order",
          "Order Details": "Order Details",
          "Customer Name :": "Customer Name :",
          "Voucher Number :": "Voucher Number :",
          "Order Time :": "Order Time :",
          "Total Items :": "Total Items :",
          "Product Name": "Product Name",
          "Qty": "Qty",
          "ERROR": "ERROR",
          "INFO": "INFO",
          "SUCCESS": "SUCCESS",
          "Please enter your Phone No...": "Please enter your Phone No...",
          "User already exist with same Mail or Phone Number":
              "User already exist with same Mail or Phone Number",
          "An error occurred. Please try again.":
              "An error occurred. Please try again.",
          "Log In": "Log In",
          "Already have an account? ": "Already have an account? ",
          "Change language": "Change language",
          "Logout": "Logout",
          "No": "No",
          "Yes": "Yes",
          "Are you sure to Logout ?": "Are you sure to Logout ?",
          "Quick Menu": "Quick Menu",
        },

        ///---------------------------------------------------------------------------------- Arabic
        'ar': {
          "Hey, Welcome Back !": "مرحبًا بعودتك!",
          "Powered By": "مدعوم من",
          "Novasoft Technologies": "نوفاسوفت تكنولوجيز",
          "Phone Number": "رقم التليفون",
          "Please enter your Phone No.": "الرجاء إدخال رقم هاتفك",
          "Password": "كلمة المرور",
          "Please enter your Password": "الرجاء إدخال كلمة المرور الخاصة بك",
          "Forgot password ?": "هل نسيت كلمة السر ؟ ",
          "Login": "تسجيل الدخول",
          "Don't have an account? ": "ليس لديك حساب؟",
          "Register": "يسجل",
          "Forgot Password": "هل نسيت كلمة السر",
          "Get OTP": "احصل على كلمة مرور لمرة واحدة",
          "Create an account !": "إنشاء حساب !",
          "Your Name": "اسمك",
          "Please enter your Name": "الرجاء إدخال اسمك",
          "Company Name": "اسم الشركة",
          "Please enter your Company Name": "الرجاء إدخال اسم شركتك",
          "Address": "عنوان",
          "Please enter your Company Address": "الرجاء إدخال عنوان شركتك",
          "VAT Number": "رقم ضريبة القيمة المضافة",
          "Please enter your VAT No.":
              "الرجاء إدخال رقم ضريبة القيمة المضافة الخاص بك.",
          "CR Number": "رقم السجل التجاري",
          "Please enter your CR No.":
              "الرجاء إدخال رقم السجل التجاري الخاص بك.",
          "Email": "بريد إلكتروني",
          "Please enter your Email": "الرجاء إدخال البريد الإلكتروني الخاص بك",
          "Confirm Password": "تأكيد كلمة المرور",
          "Please enter Password to confirm":
              "الرجاء إدخال كلمة المرور للتأكيد",
          "Already have an account?": "هل لديك حساب بالفعل؟",
          "Nahla Online": "نهلة اون لاين",
          "What are you looking for?": "ما الذي تبحث عنه؟",
          "Invoices": "الفواتير",
          "Home": "بيت",
          "Download": "تحميل",
          "Choose your Language": "اختر لغتك",
          "English": "الإنجليزية",
          "Arabic": "عربي",
          "OTP Verification": "التحقق من OTP",
          "Enter the OTP sent to": "أدخل كلمة المرور لمرة واحدة المرسلة إلى",
          "Verify": "يؤكد",
          "Orders": "طلبات",
          "Order No : ": "رقم الطلب : ",
          "Amount : ": "كمية : ",
          "Status : ": "حالة : ",
          "Last Updated : ": "آخر تحديث : ",
          "Add New Invoice": "إضافة فاتورة جديدة",
          "Required field": "الحقل المطلوب",
          "Please enter your Inv No.": "الرجاء إدخال رقم الفاتورة الخاص بك.",
          "--- OR ---": "--- أو ---",
          "Tap below barcode to start scan":
              "انقر أدناه على الرمز الشريطي لبدء المسح",
          "Add Order": "أضف الطلب",
          "Order Details": "تفاصيل الطلب",
          "Customer Name : ": "اسم العميل : ",
          "Voucher Number : ": "رقم القسيمة : ",
          "Order Time : ": "وقت الطلب : ",
          "Total Items : ": "إجمالي العناصر : ",
          "Product Name": "اسم المنتج",
          "Qty": "الكمية",
          "ERROR": "خطأ",
          "INFO": "معلومات",
          "SUCCESS": "نجاح",
          "Please enter your Phone No...": "الرجاء إدخال رقم هاتفك...",
          "User already exist with same Mail or Phone Number":
              "المستخدم موجود بالفعل بنفس البريد أو رقم الهاتف",
          "An error occurred. Please try again.":
              "حدث خطأ. يرجى المحاولة مرة أخرى.",
          "Log In": "تسجيل الدخول",
          "Already have an account? ": "هل لديك حساب بالفعل؟ ",
          "Change language": "تغيير اللغة",
          "Logout": "تسجيل الخروج",
          "No": "لا",
          "Yes": "نعم",
          "Are you sure to Logout ?": "هل أنت متأكد من تسجيل الخروج؟",
          "Quick Menu": "القائمة السريعة",
        },
      };
}
