import 'package:get/get.dart';

class AppTranslations extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        ///------------------------------------------------------------------English
        'en': {
          'ENGLISH': 'ENGLISH',
          'ARABIC': 'ARABIC',
          'VAT': 'VAT',
          'Add your phone number': 'Add your phone number',
          'Mobile Number': 'Mobile Number',
          'OTP Verification': 'OTP Verification',
          'Enter the OTP sent to': 'Enter the OTP sent to',
          'Choose your Language': 'Choose your Language',
          'English': 'English',
          'Arabic': 'Arabic',
          "Add": "Add",
          "Powered By": "Powered By",
          "Novasoft Technologies": "Novasoft Technologies",
          "LOGIN": "LOGIN",
          "Phone Number": "Phone Number",
          "Password": "Password",
          "Phone Number can't be empty": "Phone Number can't be empty",
          "Password can't be empty": "Password can't be empty",
          "Forgot Password?": "Forgot Password?",
          "Log In": "Log In",
          "Home": "Home",
          "Category": "Category",
          "Cart": "Cart",
          "Favorite": "Favorite",
          "Notification": "Notification",
          "Nahla E-Store": "Nahla E-Store",
          "What are you looking for?": "What are you looking for?",
          "Bulk Order": "Bulk Order",
          "Buy Again": "Buy Again",
          "Direct Billing": "Direct Billing",
          "Barcode Scanner": "Barcode Scanner",
          "Soft Drinks\n& Water": "Soft Drinks\n& Water",
          "Rice": "Rice",
          "Spices,\nFlour & Mill": "Spices,\nFlour & Mill",
          "Frozen": "Frozen",
          "Oil": "Oil",
          "Nuts &\nChocolates": "Nuts &\nChocolates",
          "Detergents\n& Soap": "Detergents\n& Soap",
          "Tea &\nCoffee": "Tea &\nCoffee",
          "Milk,\nGhee & Butter": "Milk,\nGhee & Butter",
          "Non Food": "Non Food",
          "Noodles, Ketchup\n& Mayonnaise": "Noodles, Ketchup\n& Mayonnaise",
          "Canned &\nPackaged Food": "Canned &\nPackaged Food",
          "Hot Deals": "Hot Deals",
          "More": "More",
          "SAR": "SAR",
          "Offer Zone": "Offer Zone",
          "My Account": "My Account",
          "Categories": "Categories",
          "Wallet": "Wallet",
          "My Orders": "My Orders",
          "Statement of Account": "Statement of Account",
          "Favourites": "Favourites",
          "My Cart": "My Cart",
          "Order History": "Order History",
          "Notifications": "Notifications",
          "Delivery Locations": "Delivery Locations",
          "Share with friends": "Share with friends",
          "Rate us on PlayStore": "Rate us on PlayStore",
          "Contact & Support": "Contact & Support",
          "Terms & Conditions": "Terms & Conditions",
          "Feedback": "Feedback",
          "FAQ": "FAQ",
          "Logout": "Logout",
          "App Version :": "App Version :",
          "Search..": "Search..",
          "Shopping Cart": "Shopping Cart",
          "Clear all": "Clear all",
          "Payable Amount :": "Payable Amount :",
          "Place Order": "Place Order",
          "Delete": "Delete",
          "Carton": "Carton",
          "In Stock": "In Stock",
          "Slide to Proceed": "Slide to Proceed",
          "Collect from Store": "Collect from Store",
          "Select Date": "Select Date",
          "Select Time": "Select Time",
          "AM/PM": "AM/PM",
          "Payment Methods": "Payment Methods",
          "Pay at Showroom": "Pay at Showroom",
          "Payment Details": "Payment Details",
          "Total Payable": "Total Payable",
          "Other Charges": "Other Charges",
          "Total": "Total",
          "Add to Cart": "Add to Cart",
          "Profile": "Profile",
          "Name": "Name",
          "Change Name": "Change Name",
          "Your New Name": "Your New Name",
          "Cancel": "Cancel",
          "OK": "OK",
          "Mobile": "Mobile",
          "Email": "Email",
          "Change Email": "Change Email",
          "Your New Email": "Your New Email",
          "Address": "Address",
          "Add Address": "Add Address",
          "Change Language": "Change Language",
          "Select Language": "Select Language",
          "Select": "Select",
          "Change Password": "Change Password",
          "Name *": "Name *",
          "Name can't be empty": "Name can't be empty",
          "House name": "House name",
          "House name can't be empty": "House name can't be empty",
          "Landmark": "Landmark",
          "Landmark can't be empty": "Landmark can't be empty",
          "City": "City",
          "City can't be empty": "City can't be empty",
          "Location": "Location",
          "Location can't be empty": "Location can't be empty",
          "Delivery Area": "Delivery Area",
          "Pincode": "Pincode",
          "Pincode can't be empty": "Pincode can't be empty",
          "Mobile Number *": "Mobile Number *",
          "Mobile Number can't be empty": "Mobile Number can't be empty",
          "SUBMIT": "SUBMIT",
          "Field can't be empty": "Field can't be empty",
          "New Password": "New Password",
          "Continue": "Continue",
          "My Wallet": "My Wallet",
          "Total Rewards": "Total Rewards",
          "Order ID -": "Order ID -",
          "Repeat Order": "Repeat Order",
          "Order No": "Order No",
          "Order Date & Time": "Order Date & Time",
          "Delivery Type": "Delivery Type",
          ": Collect from Store": ": Collect from Store",
          "Delivery on": "Delivery on",
          "Order Status": "Order Status",
          ": Order Placed": ": Order Placed",
          "Payment method": "Payment method",
          ": Cash on Delivery": ": Cash on Delivery",
          "Net Payment Amount": "Net Payment Amount",
          ": SAR": ": SAR",
          "Order Details": "Order Details",
          "Quantity": "Quantity",
          "Flavour": "Flavour",
          "Order Completed": "Order Completed",
          "Ordered on": "Ordered on",
          "Delivery Address": "Delivery Address",
          "Order ID": "Order ID",
          "Amount": "Amount",
          "Check Pincode/Area..": "Check Pincode/Area..",
          "Al Anud()": "Al Anud()",
          "WE ARE HERE": "WE ARE HERE",
          "NAHLA AL WADI TRADING CO. LLC": "NAHLA AL WADI TRADING CO. LLC",
          "Wasel 2579, Al-Anud, Unit No.1,\nDammam 32427 - 6848,\nKingdom of Saudi Arabia":
              "Wasel 2579, Al-Anud, Unit No.1,\nDammam 32427 - 6848,\nKingdom of Saudi Arabia",
          "Customer Support": "Customer Support",
          "Landline :": "Landline :",
          "Mail :": "Mail :",
          "Visit Us :": "Visit Us :",
          "Whatsapp": "Whatsapp",
          "Call": "Call",
          "Show more": "Show more",
          "Show less": "Show less",
          "Register your Feedback, Enquiry & Complaints":
              "Register your Feedback, Enquiry & Complaints",
          "Email or Mobile No": "Email or Mobile No",
          "Type your Complaints, Feedbacks & Enquiry":
              "Type your Complaints, Feedbacks & Enquiry",
          "Submit": "Submit",
          "Soft Drinks & Water": "Soft Drinks & Water",
          "BEERS": "BEERS",
          "ENERGY DRINKS": "ENERGY DRINKS",
          "JUICE": "JUICE",
          "SOFT DRINKS": "SOFT DRINKS",
          "WATER": "WATER",
          "Added to cart": "Added to cart",
          "Choose Brands": "Choose Brands",
          "CARTON": "CARTON",
          "Fliter": "Fliter",
          "Brands": "Brands",
          "Apply": "Apply",
          "Sort By": "Sort By",
          "A-Z": "A-Z",
          "Z-A": "Z-A",
          "Price Low-High": "Price Low-High",
          "Price High-Low": "Price High-Low",
          "Newest": "Newest",
          "Popularity": "Popularity",
          "BASMATI": "BASMATI",
          "JASMINE": "JASMINE",
          "JEERAKASALA": "JEERAKASALA",
          "MATTA RICE": "MATTA RICE",
          "OTHERS": "OTHERS",
          "WHITE RICE": "WHITE RICE",
          "PARMAL": "PARMAL",
          "Spices, Flour & Mill": "Spices, Flour & Mill",
          "FLOUR": "FLOUR",
          "SPICES": "SPICES",
          "PULSES": "PULSES",
          "1 KG PACK": "1 KG PACK",
          "BAGS": "BAGS",
          "PICKLES": "PICKLES",
          "CORIANDER": "CORIANDER",
          "CHILLI": "CHILLI",
          "TURMERIC": "TURMERIC",
          "CHICKEN": "CHICKEN",
          "MEAT": "MEAT",
          "PEPPER": "PEPPER",
          "CUMMIN": "CUMMIN",
          "SAMBAR": "SAMBAR",
          "MIX MASALA": "MIX MASALA",
          "BIRIYANI": "BIRIYANI",
          "FISH": "FISH",
          "BAKING": "BAKING",
          "BURGER": "BURGER",
          "FRUITS": "FRUITS",
          "OTHER": "OTHER",
          "PANEER": "PANEER",
          "POTATO": "POTATO",
          "SHRIMPS": "SHRIMPS",
          "VEG": "VEG",
          "MUTTON": "MUTTON",
          "BLENDED OIL": "BLENDED OIL",
          "COCONUT OIL": "COCONUT OIL",
          "CORN OIL": "CORN OIL",
          "MUSTARD OIL": "MUSTARD OIL",
          "OILVE OIL": "OILVE OIL",
          "SESAME OIL": "SESAME OIL",
          "SUN OIL": "SUN OIL",
          "Nuts & Chocolates": "Nuts & Chocolates",
          "BISCUITS": "BISCUITS",
          "CHEWINGUM": "CHEWINGUM",
          "CHIPS": "CHIPS",
          "CHOCOLATE": "CHOCOLATE",
          "NUTS": "NUTS",
          "PEANUT BUTTER": "PEANUT BUTTER",
          "BATH SOAP": "BATH SOAP",
          "DISHWASH": "DISHWASH",
          "SOAP POWDER": "SOAP POWDER",
          "WASH & CLEAN": "WASH & CLEAN",
          "Tea & Coffee": "Tea & Coffee",
          "COFFEE": "COFFEE",
          "GREEN TEA": "GREEN TEA",
          "TEA BAGS": "TEA BAGS",
          "TEA POWDER": "TEA POWDER",
          "Detergents & Soap": "Detergents & Soap",
          "Milk, Ghee & Butter": "Milk, Ghee & Butter",
          "Noodles,Ketchup & Mayonnaise": "Noodles,Ketchup & Mayonnaise",
          "BABY FOOD": "BABY FOOD",
          "BUTTER": "BUTTER",
          "CHEESE": "CHEESE",
          "EGG": "EGG",
          "GHEE": "GHEE",
          "MILK": "MILK",
          "CREAM": "CREAM",
          "MILK POWDER": "MILK POWDER",
          "ALU TRAY": "ALU TRAY",
          "DIAPER": "DIAPER",
          "FOIL": "FOIL",
          "FOOD PACKING": "FOOD PACKING",
          "PAPER": "PAPER",
          "HYGIENE": "HYGIENE",
          "NYLON": "NYLON",
          "TEA CUP": "TEA CUP",
          "TISSUES": "TISSUES",
          "TRASH BAGS": "TRASH BAGS",
          "PLASTIC BAGS": "PLASTIC BAGS",
          "CEREALS": "CEREALS",
          "HOT SAUCE": "HOT SAUCE",
          "KETCHUP": "KETCHUP",
          "MACRONI": "MACRONI",
          "MAYONNAISE": "MAYONNAISE",
          "NOODLES": "NOODLES",
          "TOMATO PASTE": "TOMATO PASTE",
          "Canned & Packaged Food": "Canned & Packaged Food",
          "BOTTLED": "BOTTLED",
          "CAKE MIX": "CAKE MIX",
          "CANNED": "CANNED",
          "FOOD COLOR": "FOOD COLOR",
          "HONEY": "HONEY",
          "JAM": "JAM",
          "OLIVES": "OLIVES",
          "PICKELS": "PICKELS",
          "SALT": "SALT",
          "SEASONING": "SEASONING",
          "SUGAR": "SUGAR",
          "TUNA": "TUNA",
          "VINEGAR": "VINEGAR",
          "Bulk Purchase": "Bulk Purchase",
          "Total Items : ": "Total Items : ",
          "Type your Item..": "Type your Item..",
          "Quantity can't be empty": "Quantity can't be empty",
          "Request": "Request",
          "Product": "Product",
          "Qty": "Qty",
          "Search Product..": "Search Product..",
          "Choose Unit": "Choose Unit",
          "Choose Flavour": "Choose Flavour",
          "Add Qty": "Add Qty",
          "Order List": "Order List",
          "Package Size": "Package Size",
          "Grocer": "Grocer",
          "Unit Name": "Unit Name",
          "CHOCOLATES": "CHOCOLATES",
          "Please select Date and Time": "Please select Date and Time",
          "Order Placed Successfully": "Order Placed Successfully",
          "Try Again": "Try Again",
          "You seem to be offline": "You seem to be offline",
          "Please check your Wi-Fi connection or\ncellular data and try again":
              "Please check your Wi-Fi connection or\ncellular data and try again",
          "Don't have an account ? ": "Don't have an account ? ",
          "Register": "Register",
          "Forgot Password": "Forgot Password",
          "Create an account": "Create an account",
          "Company Name": "Company Name",
          "VAT Number": "VAT Number",
          "CR Number": "CR Number",
          "Mail ID": "Mail ID",
          "Confirm Password": "Confirm Password",
          "Already have an account?": "Already have an account?",
          "Login": "Login",
          "LIMITED": "LIMITED",
          "Add to wishlist": "Add to wishlist",
          "Add to cart": "Add to cart",
          "Are you sure to confirm?": "Are you sure to confirm?",
          "Yes": "Yes",
          "No": "No",
          "Modifiers": "Modifiers",
          "Add-Ons": "Add-Ons",
          "Regular": "Regular",
          "Item added to cart": "Item added to cart",
          "Enter Counter ID": "Enter Counter ID",
          "Counter ID": "Counter ID",
          "Waiting for Payment...": "Waiting for Payment...",
          "Total Amount": "Total Amount",
          "Your session about to expire...": "Your session about to expire...",
          "Extend": "Extend"
        },

        ///---------------------------------------------------------------------------------- Arabic
        'ar': {
          'Start Order': 'ابدأ الطلب',
          'ENGLISH': 'إنجليزي',
          'ARABIC': 'عربي',
          'Dine here Or Takeaway': 'تناول العشاء هنا أو الوجبات الجاهزة',
          'Dine In': 'تناول الطعام في',
          'Take away': 'يبعد',
          'Delivery': 'توصيل',
          'Let\'s eat with': 'دعونا نأكل مع',
          'Satisfy Your Cravings': 'إرضاء رغباتك',
          'Recommended': 'مُستَحسَن',
          'View Order': 'مشاهدة الطلب',
          'All': 'الجميع',
          'Chicken': 'فرخة',
          'Beef': 'لحم',
          'VAT': 'ضريبة القيمة المضافة',
          'Add More': 'أضف المزيد',
          'Finish Order': 'إنهاء الطلب',
          'Choose Payment Method': 'اختر وسيلة الدفع',
          'CASH AT COUNTER': 'النقد في العداد',
          'CREDIT/DEBIT CARD': 'بطاقة الائتمان/الخصم',
          'Add your phone number': 'أضف رقم هاتفك',
          'Mobile Number': 'رقم الهاتف المحمول',
          'OTP Verification': 'التحقق من OTP',
          'Enter the OTP sent to': 'أدخل كلمة المرور لمرة واحدة المرسلة إلى',
          'Verify': 'يؤكد',
          'Remove': 'يزيل',
          'Default': 'تقصير',
          'Cancel Item': 'إلغاء البند',
          'Add Item': 'اضافة عنصر',
          'Order Placed': 'تم الطلب',
          'Thank You!': 'شكرًا لك!',
          'Return to Home': 'العودة إلى المنزل',
          'Pay amount ': 'مقدار الأجر',
          'at counter\nto confirm your order': 'في العداد\nلتأكيد طلبك',
          //
          'Choose your Language': 'اختر لغتك',
          'English': 'إنجليزي',
          'Arabic': 'عربي',
          "Add": "يضيف",
          "Powered By": "مشغل بواسطة",
          "Novasoft Technologies": "نوفاسوفت تكنولوجيز",
          "LOGIN": "تسجيل الدخول",
          "Phone Number": "رقم التليفون",
          "Password": "كلمة المرور",
          "Phone Number can't be empty": "لا يمكن أن يكون رقم الهاتف فارغًا",
          "Password can't be empty": "لا يمكن أن تكون كلمة المرور فارغة",
          "Forgot Password?": "هل نسيت كلمة السر؟",
          "Log In": "تسجيل الدخول",
          "Home": "بيت",
          "Category": "فئة",
          "Cart": "عربة التسوق",
          "Favorite": "مفضل",
          "Notification": "إشعار",
          "Nahla E-Store": "متجر نهلة الإلكتروني",
          "What are you looking for?": "ما الذي تبحث عنه؟",
          "Bulk Order": "طلب بالجملة",
          "Buy Again": "شراء مرة أخرى",
          "Direct Billing": "السداد المباشر",
          "Barcode Scanner": "ماسح الباركود",
          "Soft Drinks\n& Water": "المشروبات الغازية\nوالمياه",
          "Rice": "أرز",
          "Spices,\nFlour & Mill": "بهارات\nدقيق ومطحنة",
          "Frozen": "المجمدة",
          "Oil": "زيت",
          "Nuts &\nChocolates": "المكسرات والشوكولاتة",
          "Detergents\n& Soap": "المنظفات\nوالصابون",
          "Tea &\nCoffee": "الشاي والقهوة",
          "Milk,\nGhee & Butter": "الحليب والسمن والزبدة",
          "Non Food": "غير الغذائية",
          "Noodles, Ketchup\n& Mayonnaise": "نودلز، كاتشب\nومايونيز",
          "Canned &\nPackaged Food": "الأغذية المعلبة والمعبأة",
          "Hot Deals": "العروض الساخنة",
          "More": "أكثر",
          "SAR": "ريال سعودي",
          "Offer Zone": "منطقة العرض",
          "My Account": "حسابي",
          "Categories": "فئات",
          "Wallet": "محفظة",
          "My Orders": "طلباتي",
          "Statement of Account": "كشف حساب",
          "Favourites": "المفضلة",
          "My Cart": "سلة التسوق الخاصة بي",
          "Order History": "تاريخ الطلب",
          "Notifications": "إشعارات",
          "Delivery Locations": "مواقع التسليم",
          "Share with friends": "شارك مع الاصدقاء",
          "Rate us on PlayStore": "قيمنا على PlayStore",
          "Contact & Support": "اتصل بالدعم",
          "Terms & Conditions": "البنود و الظروف",
          "Feedback": "تعليق",
          "FAQ": "التعليمات",
          "Logout": "تسجيل خروج",
          "App Version :": "نسخة التطبيق :",
          "Search..": "يبحث..",
          "Shopping Cart": "عربة التسوق",
          "Clear all": "امسح الكل",
          "Payable Amount :": "المبلغ المستحق :",
          "Place Order": "مكان الامر",
          "Delete": "يمسح",
          "Carton": "كرتون",
          "In Stock": "في الأوراق المالية",
          "Slide to Proceed": "حرك للمتابعة",
          "Collect from Store": "جمع من المتجر",
          "Select Date": "حدد تاريخ",
          "Select Time": "حدد الوقت",
          "AM/PM": "صباحا مساءا",
          "Payment Methods": "طرق الدفع",
          "Pay at Showroom": "الدفع في صالة العرض",
          "Payment Details": "بيانات الدفع",
          "Total Payable": "مجموع المستحق الدفع",
          "Other Charges": "رسوم أخرى",
          "Total": "المجموع",
          "Add to Cart": "أضف إلى السلة",
          "Profile": "حساب تعريفي",
          "Name": "اسم",
          "Change Name": "تغيير الإسم",
          "Your New Name": "اسمك الجديد",
          "Cancel": "يلغي",
          "OK": "نعم",
          "Mobile": "متحرك",
          "Email": "بريد إلكتروني",
          "Change Email": "تغيير الايميل",
          "Your New Email": "بريدك الإلكتروني الجديد",
          "Address": "عنوان",
          "Add Address": "اضف عنوان",
          "Change Language": "تغيير اللغة",
          "Select Language": "اختار اللغة",
          "Select": "يختار",
          "Change Password": "تغيير كلمة المرور",
          "Name *": "اسم *",
          "Name can't be empty": "لا يمكن أن يكون الاسم فارغًا",
          "House name": "اسم المنزل",
          "House name can't be empty": "لا يمكن أن يكون اسم المنزل فارغًا",
          "Landmark": "معلم معروف",
          "Landmark can't be empty": "لا يمكن أن يكون المعلم فارغًا",
          "City": "مدينة",
          "City can't be empty": "لا يمكن أن تكون المدينة فارغة",
          "Location": "موقع",
          "Location can't be empty": "لا يمكن أن يكون الموقع فارغًا",
          "Delivery Area": "منطقة التسليم",
          "Pincode": "الرمز السري",
          "Pincode can't be empty": "لا يمكن أن يكون الرمز السري فارغًا",
          "Mobile Number *": "رقم الهاتف المحمول *",
          "Mobile Number can't be empty":
              "لا يمكن أن يكون رقم الهاتف المحمول فارغاً",
          "SUBMIT": "يُقدِّم",
          "Field can't be empty": "لا يمكن أن يكون الحقل فارغاً",
          "New Password": "كلمة المرور الجديدة",
          "Continue": "يكمل",
          "My Wallet": "محفظتى",
          "Total Rewards": "إجمالي المكافآت",
          "Order ID -": "رقم التعريف الخاص بالطلب -",
          "Repeat Order": "اعد الامر",
          "Order No": "رقم الطلب",
          "Order Date & Time": "تاريخ الطلب والوقت",
          "Delivery Type": "نوع التوصيل",
          ": Collect from Store": ": اجمع من المتجر",
          "Delivery on": "التسليم على",
          "Order Status": "حالة الطلب",
          ": Order Placed": ": تم الطلب",
          "Payment method": "طريقة الدفع او السداد",
          ": Cash on Delivery": ": الدفع عند الاستلام",
          "Net Payment Amount": "صافي مبلغ الدفع",
          ": SAR": ": ريال سعودي",
          "Order Details": "تفاصيل الطلب",
          "Quantity": "كمية",
          "Flavour": "نكهة",
          "Order Completed": "تم اكتمال الطلب",
          "Ordered on": "أمر على",
          "Delivery Address": "عنوان التسليم",
          "Order ID": "رقم التعريف الخاص بالطلب",
          "Amount": "كمية",
          "Check Pincode/Area..": "تحقق من الرمز السري/المنطقة..",
          "Al Anud()": "أل عند()",
          "WE ARE HERE": "نحن هنا",
          "NAHLA AL WADI TRADING CO. LLC": "نهلة أل وادي تردينج كه. لك",
          "Wasel 2579, Al-Anud, Unit No.1,\nDammam 32427 - 6848,\nKingdom of Saudi Arabia":
              "واصل 2579 العنود وحدة رقم 1\nالدمام 32427 - 6848\nالمملكة العربية السعودية",
          "Customer Support": "دعم العملاء",
          "Landline :": "هاتف ارضي :",
          "Mail :": "بريد :",
          "Visit Us :": "زورنا :",
          "Whatsapp": "واتس اب",
          "Call": "يتصل",
          "Show more": "أظهر المزيد",
          "Show less": "عرض أقل",
          "Register your Feedback, Enquiry & Complaints":
              "سجل ملاحظاتك والاستفسارات والشكاوى",
          "Email or Mobile No": "البريد الإلكتروني أو رقم الجوال",
          "Type your Complaints, Feedbacks & Enquiry":
              "اكتب الشكاوى والملاحظات والاستفسارات",
          "Submit": "يُقدِّم",
          "Soft Drinks & Water": "المشروبات الغازية والمياه",
          "BEERS": "بيرة",
          "ENERGY DRINKS": "مشروبات الطاقة",
          "JUICE": "عصير",
          "SOFT DRINKS": "المشروبات الغازية",
          "WATER": "ماء",
          "Added to cart": "تمت إضافته إلى سلة التسوق",
          "Choose Brands": "اختر العلامات التجارية",
          "CARTON": "كرتون",
          "Fliter": "بريق",
          "Brands": "العلامات التجارية",
          "Apply": "يتقدم",
          "Sort By": "ترتيب حسب",
          "A-Z": "أ - ي",
          "Z-A": "ض - أ",
          "Price Low-High": "السعر منخفض مرتفع",
          "Price High-Low": "السعر مرتفع ومنخفض",
          "Newest": "الأحدث",
          "Popularity": "شعبية",
          "BASMATI": "بسمتي",
          "JASMINE": "ياسمين",
          "JEERAKASALA": "جيراكاسالا",
          "MATTA RICE": "أرز مجنون",
          "OTHERS": "آحرون",
          "WHITE RICE": "أرز أبيض",
          "PARMAL": "بارمال",
          "Spices, Flour & Mill": "التوابل والدقيق والمطحنة",
          "FLOUR": "دقيق",
          "SPICES": "بهارات",
          "PULSES": "نبضات",
          "1 KG PACK": "علبة 1 كيلو",
          "BAGS": "أكياس",
          "PICKLES": "مخللات",
          "CORIANDER": "كسبرة",
          "CHILLI": "الفلفل الحار",
          "TURMERIC": "كُركُم",
          "CHICKEN": "فرخة",
          "MEAT": "لحمة",
          "PEPPER": "الفلفل",
          "CUMMIN": "الكمون",
          "SAMBAR": "سامبار",
          "MIX MASALA": "مزيج ماسالا",
          "BIRIYANI": "برياني",
          "FISH": "سمكة",
          "BAKING": "الخبز",
          "BURGER": "برجر",
          "FRUITS": "الفاكهة",
          "OTHER": "آخر",
          "PANEER": "بانير",
          "POTATO": "البطاطس",
          "SHRIMPS": "جمبري",
          "VEG": "نباتي",
          "MUTTON": "لحم الضأن",
          "BLENDED OIL": "زيت ممزوج",
          "COCONUT OIL": "زيت جوز الهند",
          "CORN OIL": "زيت الذرة",
          "MUSTARD OIL": "زيت الخردل",
          "OILVE OIL": "زيت الزيتون",
          "SESAME OIL": "زيت السمسم",
          "SUN OIL": "زيت الشمس",
          "Nuts & Chocolates": "المكسرات والشوكولاتة",
          "BISCUITS": "بسكويت",
          "CHEWINGUM": "علكة",
          "CHIPS": "رقائق",
          "CHOCOLATE": "شوكولاتة",
          "NUTS": "المكسرات",
          "PEANUT BUTTER": "زبدة الفول السوداني",
          "BATH SOAP": "صابونة الحمام",
          "DISHWASH": "غسل الطبق",
          "SOAP POWDER": "مسحوق الصابون",
          "WASH & CLEAN": "غسل وتنظيف",
          "Tea & Coffee": "شاى و قهوة",
          "COFFEE": "قهوة",
          "GREEN TEA": "شاي أخضر",
          "TEA BAGS": "أكياس الشاي",
          "TEA POWDER": "مسحوق الشاي",
          "Detergents & Soap": "المنظفات والصابون",
          "Milk, Ghee & Butter": "الحليب والسمن والزبدة",
          "Noodles,Ketchup & Mayonnaise": "نودلز، كاتشب و مايونيز",
          "BABY FOOD": "أغذية الأطفال",
          "BUTTER": "سمنة",
          "CHEESE": "جبنه",
          "EGG": "بيضة",
          "GHEE": "السمن",
          "MILK": "لبن",
          "CREAM": "كريم",
          "MILK POWDER": "حليب مجفف",
          "ALU TRAY": "صينية ألو",
          "DIAPER": "حفاضات",
          "FOIL": "رقائق",
          "FOOD PACKING": "تعبئة المواد الغذائية",
          "PAPER": "ورق",
          "HYGIENE": "صحة",
          "NYLON": "نايلون",
          "TEA CUP": "كوب شاي",
          "TISSUES": "مناديل",
          "TRASH BAGS": "اكياس نفايات",
          "PLASTIC BAGS": "اكياس بلاستيك",
          "CEREALS": "الحبوب",
          "HOT SAUCE": "صلصة حارة",
          "KETCHUP": "كاتشب",
          "MACRONI": "ماكروني",
          "MAYONNAISE": "مايونيز",
          "NOODLES": "المعكرونة",
          "TOMATO PASTE": "معجون الطماطم",
          "Canned & Packaged Food": "الأغذية المعلبة والمعبأة",
          "BOTTLED": "المعبأة في زجاجات",
          "CAKE MIX": "خليط الكعكة",
          "CANNED": "معلب",
          "FOOD COLOR": "لون الطعام",
          "HONEY": "عسل",
          "JAM": "مربى",
          "OLIVES": "زيتون",
          "PICKELS": "المخللات",
          "SALT": "ملح",
          "SEASONING": "توابل",
          "SUGAR": "سكر",
          "TUNA": "تونة",
          "VINEGAR": "خل",
          "Bulk Purchase": "الشراء بالجملة",
          "Total Items : ": "إجمالي العناصر :",
          "Type your Item..": "اكتب السلعة الخاصة بك..",
          "Quantity can't be empty": "لا يمكن أن تكون الكمية فارغة",
          "Request": "طلب",
          "Product": "منتج",
          "Qty": "الكمية",
          "Search Product..": "بحث عن منتج..",
          "Choose Unit": "اختر الوحدة",
          "Choose Flavour": "اختر النكهة",
          "Add Qty": "أضف الكمية",
          "Order List": "لائحة الطلبات",
          "Package Size": "حجم العبوة",
          "Grocer": "بقال",
          "Unit Name": "إسم الوحدة",
          "CHOCOLATES": "الشوكولاتة",
          "Please select Date and Time": "الرجاء تحديد التاريخ والوقت",
          "Order Placed Successfully": "تم تقديم الطلب بنجاح",
          "Try Again": "حاول ثانية",
          "You seem to be offline": "يبدو أنك غير متصل",
          "Please check your Wi-Fi connection or\ncellular data and try again":
              "الرجاء التحقق من اتصال Wi-Fi أو\nبيانات شبكة الجوال والمحاولة مرة أخرى",
          "Don't have an account?": "ليس لديك حساب ؟",
          "Register": "يسجل",
          "Forgot Password": "هل نسيت كلمة السر",
          "Create an account": "إنشاء حساب",
          "Company Name": "اسم الشركة",
          "VAT Number": "ظريبه الشراء",
          "CR Number": "رقم السجل التجاري",
          "Mail ID": "رقم البريد",
          "Confirm Password": "تأكيد كلمة المرور",
          "Already have an account?": "هل لديك حساب؟",
          "Login": "تسجيل الدخول",
          "LIMITED": "محدود",
          "Add to wishlist": "أضف إلى قائمة الامنيات",
          "Add to cart": "أضف إلى السلة",
          "Tap to view more": "انقر لعرض المزيد",
          "Are you sure to confirm?": "هل أنت متأكد من التأكيد؟", "Yes": "نعم",
          "No": "لا",
          "Modifiers": "المعدلات",
          "Add-Ons": "الإضافات",
          "Regular": "عادي",
          "Item added to cart": "تمت إضافة العنصر إلى سلة التسوق",
          "Enter Counter ID": "أدخل معرف العداد",
          "Counter ID": "معرف العداد",
          "Waiting for Payment...": "في انتظار الدفع...",
          "Total Amount": "المبلغ الإجمالي",
          "Your session about to expire...": "جلستك على وشك الإنتهاء...",
          "Extend": "يمتد"
        },
      };
}
